paths:
  /api/feedback:
    get:
      summary: Retrieves all feedbacks
      tags:
        - Feedback
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FeedbackResponse'
        500:
          description: Internal Server Error
        404:
          description: No record found
        401:
          description: User un-authorized
      security:
        - JWTAuth: []
    post:
      summary: Create a new feedback
      tags:
        - Feedback
      security:
        - JWTAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeedbackSchema"
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedbackSchema"
        '400':
          description: Invalid request body
        '500':
          description: Internal Server Error
  /api/feedback/product:
    get:
      summary: Get Feedbacks for specific Product 
      tags:
        - Feedback
      security:
        - JWTAuth: []
      parameters:
        - in: query
          name: product_id
          required: true
          schema:
            type: string
          description: ID of the product to retrieve feedbacks for
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    feedback_id:
                      type: string
                      description: ID of the feedback
                    comment:
                      type: string
                      description: Comment for the feedback
                    rating:
                      type: number
                      description: Rating for the feedback
        '404':
          description: No feedbacks found for the product
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
  /api/feedback/{id}:
    put:
      summary: Update a feedback
      tags:
        - Feedback
      security:
        - JWTAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the feedback template to update
          schema:
            type: string
      requestBody:
        description: Feedback to update
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeedbackSchema"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedbackSchema"
        500:
          description: Internal Server Error
        404:
          description: No record found
    delete:
        summary: Delete a feedback  by ID
        tags:
          - Feedback 
        security:
          - JWTAuth: []
        parameters:
          - in: path
            name: id
            required: true
            description: ID of the feedback  to delete
            schema:
              type: string
        responses:
          '200':
            description: Feedback  successfully deleted
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/FeedbackSchema'
          500:
            description: Internal Server Error
          404:
            description: No record found
components:
  schemas:
    FeedbackSchema:
      type: object
      properties:
        user_id:
          type: string
          description: ID of the user who gave the feedback.
          example: 612f45d5fa301d5f77e5d5af
        deliveryagent_id:
          type: string
          description: ID of the delivery agent for whom the feedback is given.
          example: 613f54d5fa301d5f77e5d5af
        client_id:
          type: string
          description: ID of the client for whom the feedback is given.
          example: 611f44d5fa301d5f77e5d5af
        product_id:
          type: string
          description: ID of the product for which the feedback is given.
          example: 614f45d5fa301d5f77e5d5af
        template_id:
          type: string
          description: ID of the feedback template used for the feedback.
          example: 615f45d5fa301d5f77e5d5af
        rating:
          type: number
          description: Numeric rating given in the feedback.
          example: 4.5
        comment:
          type: string
          description: Optional comment given in the feedback.
          example: "The delivery was fast and efficient."
        feedback_type:
          type: number
          description: Type of feedback given.
          example: 1
        feedback_language:
          type: number
          description: Language in which the feedback is given.
          example: 1
        additional_fields:
          type: object
          description: Additional fields given in the feedback.
          example:
            field1: "value1"
            field2: "value2"
        qas:
          type: object
          description: Questions and answers given in the feedback.
          example:
            Q1: "A1"
            Q2: "A2"
      required:
        - user_id
        - rating
      example:
        user_id: 612f45d5fa301d5f77e5d5af
        deliveryagent_id: 613f54d5fa301d5f77e5d5af
        client_id: 611f44d5fa301d5f77e5d5af
        product_id: 614f45d5fa301d5f77e5d5af
        template_id: 615f45d5fa301d5f77e5d5af
        rating: 4.5
        comment: "The delivery was fast and efficient."
        feedback_type: 1
        feedback_language: 1
        additional_fields:
          field1: "value1"
          field2: "value2"
        qas:
          Q1: "A1"
          Q2: "A2"
    FeedbackResponse:
      type: object
      properties:
        feedback_id:
          type: string
          description: The ID of the feedback.
        user_id:
          type: string
          description: The ID of the user.
        product:
          type: string
          description: The ID of the product.
        rating:
          type: number
          description: The rating given in the feedback.
        Comment:
          type: string
          description: The comment provided in the feedback.
        review:
          type: object
          properties:
            property1:
              type: string
              description: Property 1 of the review.
            property2:
              type: number
              description: Property 2 of the review.
            # Add additional properties as needed
          example:
            property1: Value 1
            property2: 5
        QA:
          type: object
          properties:
            question1:
              type: string
              description: Question 1 of the QA.
            question2:
              type: string
              description: Question 2 of the QA.
            # Add additional questions as needed
          example:
            question1: Answer 1
            question2: Answer 2
        created_at:
          type: string
          format: date-time
          description: The timestamp when the feedback was created.
        updated_at:
          type: string
          format: date-time
          description: The timestamp when the feedback was last updated.
  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT