
paths:
  /api/feedbackTemplate:
    get:
      summary: Retrieves all feedback templates
      tags:
        - Feedback Template
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FeedbackTemplate'
        500:
          description: Internal Server Error
        404:
          description: No record found
        401:
          description: User un-authorized
      security:
        - JWTAuth: []
    post:
      summary: Create a new feedback form template
      tags:
        - Feedback Template
      security:
        - JWTAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeedbackFormBodySchema'
            example:
              businessCategory: 1
              businessType: 1
              feedbackFormName: E-commerce feedbacks
              formats:
                - title: product
                  order: 1
                  fields:
                    - question: How was the quality of product?
                      answerFormat:
                        - type: boolean
                          required: true
                        - type: text
                          required: false
                      order: 1
                    - question: Was there any defects in product?
                      answerFormat:
                        - type: radio
                          options:
                            - options1
                            - options2
                            - options3
                          required: true
                      order: 2
                - title: packaging
                  order: 2
                  fields:
                    - question: How was the packaging of the product?
                      answerFormat:
                        - type: starrating
                          upperBound: 10
                          required: false
                      order: 1
                - title: delivery
                  order: 3
                  fields:
                    - question: Was the delivery on-time?
                      answerFormat:
                        - type: boolean
                          required: false
                      order: 1
      responses:
        '200':
          description: Feedback form created successfully
        '400':
          description: Invalid request body
  /api/feedbackTemplate/{id}:
    put:
      summary: Update a feedback template
      tags:
        - Feedback Template
      security:
        - JWTAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the feedback template to update
          schema:
            type: string
      requestBody:
        description: Feedback template object to update
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeedbackTemplate"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedbackTemplate"
        500:
          description: Internal Server Error
        404:
          description: No record found
    delete:
        summary: Delete a feedback template by ID
        tags:
          - Feedback Template
        security:
          - JWTAuth: []
        parameters:
          - in: path
            name: id
            required: true
            description: ID of the feedback template to delete
            schema:
              type: string
        responses:
          '200':
            description: Feedback template successfully deleted
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/FeedbackTemplate'
          500:
            description: Internal Server Error
          404:
            description: No record found
components:
  schemas:
    AnswerFormat:
      type: object
      properties:
        type:
          type: string
          enum:
            - boolean
            - text
            - radio
            - select
            - multiselect
            - checkbox
            - starrating
            - numberrating
            - emojirating
          description: Type of the answer format
        required:
          type: boolean
          description: Whether the answer format is required
        options:
          type: array
          items:
            type: string
          description: List of options for select, multiselect, radio, and checkbox types
        upperBound:
          type: number
          description: Upper bound for starrating, numberrating, and emojirating types
      required:
        - type
        - required
    QuestionAnswerFormField:
      type: object
      properties:
        id:
          type: number
          description: Unique identifier for the field
        question:
          type: string
          description: Question for the field
        order:
          type: number
          description: Order of the field
        answerFormat:
          type: array
          items:
            $ref: '#/components/schemas/AnswerFormat'
          description: List of answer formats for the field
      required:
        - id
        - question
        - order
        - answerFormat
    FeedbackFormat:
      type: object
      properties:
        id:
          type: number
          description: Unique identifier for the format
        title:
          type: string
          description: Title of the format
        order:
          type: number
          description: Order of the format
        fields:
          type: array
          items:
            $ref: '#/components/schemas/QuestionAnswerFormField'
          description: List of fields in the format
      required:
        - id
        - title
        - order
    FeedbackFormBodySchema:
      type: object
      properties:
        businessCategory:
          type: number
          description: Business category
        businessType:
          type: number
          description: Business type
        feedbackFormName:
          type: string
          description: Name of the feedback form
        formats:
          type: array
          items:
            $ref: '#/components/schemas/FeedbackFormat'
          description: List of feedback formats
      required:
        - businessType
        - feedbackFormName
        - formats
    FeedbackQuestion:
      type: object
      properties:
        question:
          type: string
        answerFormat:
          type: string
          enum:
            - enum_value_1
            - enum_value_2
            - enum_value_3
          description: Enum values for answer format
      required:
        - question
        - answerFormat
    FeedbackTemplate:
      type: object
      properties:
        template_type:
          type: string
          enum:
            - enum_value_1
            - enum_value_2
            - enum_value_3
          description: Enum values for template type
        business_type:
          type: string
          enum:
            - enum_value_1
            - enum_value_2
            - enum_value_3
          description: Enum values for business type
        requiredFields:
          type: object
          additionalProperties:
            type: boolean
        qas:
          type: array
          items:
            $ref: '#/components/schemas/FeedbackQuestion'
        client_id:
          type: number
        isActive:
          type: boolean
      required:
        - type
        - businesstype
        - requiredFields
        - qas
        - client_id
        - isActive
      example:
        _id: 617f814ef139c17f53e4e1c4
        template_type: "1"
        business_type: "1"
        requiredFields:
          rating: true
          comment: false
        qas:
          Q1:
            question: "What do you think about the quality of the product?"
            answerFormat: "1"
          Q2:
            question: "How was your experience with the delivery of the product?"
            answerFormat: "3"
          Q3:
            question: "Would you recommend our product to others ?"
            answerFormat: "2"
        isActive: true
        clientId: d1bb78ca-d9e1-4f72-b4d7-677e8ecb3172
        createdAt: '2022-05-11T10:35:20.543Z'
        updatedAt: '2022-05-11T10:35:20.543Z'
  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT